In [1]:
import numpy as np
import pandas as pd


                                                     Creating a DataFrame

In [2]:
# when u use dictionary you can set columns name as a key then u do not set columns name manually
data={
    'Name':['John','Anna','Peter','Linda'],
    'Age':[28,34,29,42],
    'City':['New York','Paris','Berlin','London'],
    'Salary':[65000,70000,62000,85000]
}

pd.DataFrame(data)

    Name  Age      City  Salary
0   John   28  New York   65000
1   Anna   34     Paris   70000
2  Peter   29    Berlin   62000
3  Linda   42    London   85000

In [3]:
# when u use list then u need to set columns name manually example
data_list=[
    ['John',28,'New York',65000],
    ['Anna',34,'Paris',70000],
    ['peter',29,'Berlin',62000],
    ['Linda',42,'London',85000]
]

df1=pd.DataFrame(data_list)
df1

       0   1         2      3
0   John  28  New York  65000
1   Anna  34     Paris  70000
2  peter  29    Berlin  62000
3  Linda  42    London  85000

In [4]:
#set manually
col=["name","Age","City","Salary"]
df2=pd.DataFrame(data_list,columns=col)
df2

    name  Age      City  Salary
0   John   28  New York   65000
1   Anna   34     Paris   70000
2  peter   29    Berlin   62000
3  Linda   42    London   85000


                                           Selection and indexing of Columns

In [5]:
data_list=[
    ['John',28,'New York',65000],
    ['Anna',34,'Paris',70000],
    ['peter',29,'Berlin',62000],
    ['Linda',42,'London',85000]
]

col=["Name","Age","City","Salary"]
df2=pd.DataFrame(data_list,columns=col)
df2

    Name  Age      City  Salary
0   John   28  New York   65000
1   Anna   34     Paris   70000
2  peter   29    Berlin   62000
3  Linda   42    London   85000

In [6]:
# access a single columns
df2['Name']

0     John
1     Anna
2    peter
3    Linda
Name: Name, dtype: object

In [7]:
# access a multiple colums at a time
df2[['Name','City','Age']]

    Name      City  Age
0   John  New York   28
1   Anna     Paris   34
2  peter    Berlin   29
3  Linda    London   42

In [8]:
# Add a new columns in the data Frame
df2["Designation"]=["Doctor","Student","Teacher","Engineer"]
df2

    Name  Age      City  Salary Designation
0   John   28  New York   65000      Doctor
1   Anna   34     Paris   70000     Student
2  peter   29    Berlin   62000     Teacher
3  Linda   42    London   85000    Engineer


                                             Remove columns and Rows

In [9]:
# if you do not use inplace key word then it do not remove permanently
df2.drop('Designation',axis=1)

    Name  Age      City  Salary
0   John   28  New York   65000
1   Anna   34     Paris   70000
2  peter   29    Berlin   62000
3  Linda   42    London   85000

In [10]:
# this time use implace 
df2.drop('Designation',axis=1,inplace=True)
df2

    Name  Age      City  Salary
0   John   28  New York   65000
1   Anna   34     Paris   70000
2  peter   29    Berlin   62000
3  Linda   42    London   85000

In [11]:
# if you want remove multiple colmuns
df2.drop(['Name','City'],axis=1)

   Age  Salary
0   28   65000
1   34   70000
2   29   62000
3   42   85000

In [12]:
# if you want remove Row
df2.drop(0,axis=0)

    Name  Age    City  Salary
1   Anna   34   Paris   70000
2  peter   29  Berlin   62000
3  Linda   42  London   85000



                                           Selecting Row

In [13]:
df2

    Name  Age      City  Salary
0   John   28  New York   65000
1   Anna   34     Paris   70000
2  peter   29    Berlin   62000
3  Linda   42    London   85000

In [14]:
# if i want access the first row
df2.loc[0]

Name          John
Age             28
City      New York
Salary       65000
Name: 0, dtype: object

In [15]:
# if i want to access multiple row
df2.loc[[0,1]]

   Name  Age      City  Salary
0  John   28  New York   65000
1  Anna   34     Paris   70000



                                   Selecting Subsets of rows and Columns

In [16]:
df2.loc[[0,1]][["City","Salary"]]

       City  Salary
0  New York   65000
1     Paris   70000

In [17]:
df2.loc[[2,3]][["Name","Age"]]

    Name  Age
2  peter   29
3  Linda   42



                                              Condition selection

In [18]:
df2

    Name  Age      City  Salary
0   John   28  New York   65000
1   Anna   34     Paris   70000
2  peter   29    Berlin   62000
3  Linda   42    London   85000

In [19]:
# I only want to see those people whose age is above 30
df2[df2["Age"]>30]

    Name  Age    City  Salary
1   Anna   34   Paris   70000
3  Linda   42  London   85000

In [20]:
# I only want to see those people whose age is abvoe 30 and city is Paris

df2[(df2["Age"]>30) & (df2["City"]=='Paris')]

   Name  Age   City  Salary
1  Anna   34  Paris   70000