In [1]:
import pandas as pd

data = {
    "date": ["2025-01-01", "2025-02-15", "2025-03-10"]
}

df=pd.DataFrame(data)

df['date']=pd.to_datetime(df['date'])

In [2]:
#🧠 2. Extract parts (.dt)

df['year']=df['date'].dt.year
df['month']=df['date'].dt.month
df['day']=df['date'].dt.day
df['week day']=df['date'].dt.day_name()
df['month name']=df['date'].dt.month_name()

df

        date  year  month  day   week day month name
0 2025-01-01  2025      1    1  Wednesday    January
1 2025-02-15  2025      2   15   Saturday   February
2 2025-03-10  2025      3   10     Monday      March

In [3]:
#⏳ 3. Time difference
import pandas as pd

df = pd.DataFrame({
    "start": ["2025-01-01", "2025-01-10"],
    "end": ["2025-01-05", "2025-01-20"]
})

df['start']=pd.to_datetime(df['start'])
df['end']=pd.to_datetime(df['end'])

df['diff']=(df['end']-df['start'])

df

       start        end    diff
0 2025-01-01 2025-01-05  4 days
1 2025-01-10 2025-01-20 10 days

In [4]:
#shift key word

import pandas as pd

df = pd.DataFrame({
    "date": ["2025-01-01", "2025-01-21", "2025-02-01"]
})

df['date']=pd.to_datetime(df['date'])
df.sort_values('date')

df['prev_date']=df['date'].shift(1)

df['gap_day']=df['date']-df['prev_date']

df

        date  prev_date gap_day
0 2025-01-01        NaT     NaT
1 2025-01-21 2025-01-01 20 days
2 2025-02-01 2025-01-21 11 days

In [5]:
import pandas as pd

df = pd.DataFrame({
    "start": ["2025-01-01 10:00:00"],
    "end": ["2025-01-03 12:00:00"]
})

df['start'] = pd.to_datetime(df['start'])
df['end'] = pd.to_datetime(df['end'])

df['diff'] = df['end'] - df['start']

df['days'] = df['diff'].dt.days
df['hours'] = df['diff'].dt.total_seconds() / 3600

df

                start                 end            diff  days  hours
0 2025-01-01 10:00:00 2025-01-03 12:00:00 2 days 02:00:00     2   50.0

In [6]:
#⏩ 6. Add / subtract time
import pandas as pd

df = pd.DataFrame({
    "date": ["2025-01-01", "2025-01-10"]
})

df['date']=pd.to_datetime(df['date'])

df['next_day']=df['date']+pd.Timedelta(days=35)
df['prev_day']=df['date']-pd.Timedelta(days=9)

df

        date   next_day   prev_day
0 2025-01-01 2025-02-05 2024-12-23
1 2025-01-10 2025-02-14 2025-01-01