In [3]:
import numpy as np
import pandas as pd

df=pd.read_csv('student_completed_data.csv')
df.loc[df['FullName']=='Afsana Mimi','Total Marks']=np.nan
df.loc[df['FullName']=='Sadia Chowdhury','Total Marks']=np.nan
df.loc[df['FullName']=='Alif Rahman','Total Marks']=np.nan

df

,StudentID,FullName,CompletionStatus,EnrollmentDate,FinishedDate,Instructor,Location,Total Marks
0,PH0001,Alif Rahman,Completed,2024-09-01,2024-12-23,Ms. Salma,Khulna,NaN
1,PH0002,Fatima Akhter,Completed,2024-08-11,2024-11-07,Mr. Karim,Dhaka,271.0
2,PH0003,Imran Hossain,Completed,2024-05-08,2024-08-08,Ms. Salma,Dhaka,269.0
3,PH0004,Jannatul Ferdous,Completed,2024-07-05,2024-09-23,Mr. Karim,Khulna,270.0
4,PH0005,Kamal Uddin,Completed,2024-02-01,2024-04-17,Mr. David,Sylhet,254.0
5,PH0006,Laila Begum,Completed,2024-09-07,2024-12-31,Mr. David,Khulna,272.0
6,PH0007,Mahmudul Hasan,Completed,2024-06-07,2024-07-20,Mr. David,Chattogram,249.0
7,PH0008,Nadia Islam,Completed,2024-03-22,2024-05-01,Ms. Salma,Khulna,246.0
8,PH0009,Omar Faruq,Completed,2024-02-12,2024-06-08,Mr. Karim,Dhaka,291.0
9,PH0010,Priya Sharma,Completed,2024-06-19,2024-08-19,Mr. David,Dhaka,286.0
10,PH0011,Rahim Sheikh,Completed,2024-03-14,2024-06-11,Mr. Karim,Sylhet,283.0
11,PH0012,Sadia Chowdhury,Completed,2024-08-04,2024-10-25,Mr. Karim,Sylhet,NaN
12,PH0013,Tanvir Ahmed,Completed,2024-06-07,2024-08-03,Mr. David,Dhaka,248.0
13,PH0014,Urmi Akter,Completed,2024-01-04,2024-03-23,Mr. David,Sylhet,285.0
14,PH0015,Wahiduzzaman,Completed,2024-02-22,2024-05-16,Mr. David,Rajshahi,291.0
15,PH0016,Ziaur Rahman,Completed,2024-03-23,2024-06-21,Ms. Salma,Rajshahi,234.0
16,PH0017,Afsana Mimi,Completed,2024-01-18,2024-03-16,Mr. David,Khulna,NaN
17,PH0018,Babul Ahmed,Completed,2024-06-23,2024-09-20,Mr. David,Dhaka,278.0
18,PH0019,Faria Rahman,Completed,2024-04-19,2024-08-17,Mr. Karim,Sylhet,277.0
19,PH0020,Tariq Hasan,Completed,2024-07-21,2024-10-11,Mr. Karim,Khulna,253.0

In [5]:
instructor_group=df.groupby('Instructor')

for instructor,df_ins in instructor_group:
    print(instructor)
    display(df_ins)

Mr. David

,StudentID,FullName,CompletionStatus,EnrollmentDate,FinishedDate,Instructor,Location,Total Marks
4,PH0005,Kamal Uddin,Completed,2024-02-01,2024-04-17,Mr. David,Sylhet,254.0
5,PH0006,Laila Begum,Completed,2024-09-07,2024-12-31,Mr. David,Khulna,272.0
6,PH0007,Mahmudul Hasan,Completed,2024-06-07,2024-07-20,Mr. David,Chattogram,249.0
9,PH0010,Priya Sharma,Completed,2024-06-19,2024-08-19,Mr. David,Dhaka,286.0
12,PH0013,Tanvir Ahmed,Completed,2024-06-07,2024-08-03,Mr. David,Dhaka,248.0
13,PH0014,Urmi Akter,Completed,2024-01-04,2024-03-23,Mr. David,Sylhet,285.0
14,PH0015,Wahiduzzaman,Completed,2024-02-22,2024-05-16,Mr. David,Rajshahi,291.0
16,PH0017,Afsana Mimi,Completed,2024-01-18,2024-03-16,Mr. David,Khulna,NaN
17,PH0018,Babul Ahmed,Completed,2024-06-23,2024-09-20,Mr. David,Dhaka,278.0

Mr. Karim

,StudentID,FullName,CompletionStatus,EnrollmentDate,FinishedDate,Instructor,Location,Total Marks
1,PH0002,Fatima Akhter,Completed,2024-08-11,2024-11-07,Mr. Karim,Dhaka,271.0
3,PH0004,Jannatul Ferdous,Completed,2024-07-05,2024-09-23,Mr. Karim,Khulna,270.0
8,PH0009,Omar Faruq,Completed,2024-02-12,2024-06-08,Mr. Karim,Dhaka,291.0
10,PH0011,Rahim Sheikh,Completed,2024-03-14,2024-06-11,Mr. Karim,Sylhet,283.0
11,PH0012,Sadia Chowdhury,Completed,2024-08-04,2024-10-25,Mr. Karim,Sylhet,NaN
18,PH0019,Faria Rahman,Completed,2024-04-19,2024-08-17,Mr. Karim,Sylhet,277.0
19,PH0020,Tariq Hasan,Completed,2024-07-21,2024-10-11,Mr. Karim,Khulna,253.0

Ms. Salma

,StudentID,FullName,CompletionStatus,EnrollmentDate,FinishedDate,Instructor,Location,Total Marks
0,PH0001,Alif Rahman,Completed,2024-09-01,2024-12-23,Ms. Salma,Khulna,NaN
2,PH0003,Imran Hossain,Completed,2024-05-08,2024-08-08,Ms. Salma,Dhaka,269.0
7,PH0008,Nadia Islam,Completed,2024-03-22,2024-05-01,Ms. Salma,Khulna,246.0
15,PH0016,Ziaur Rahman,Completed,2024-03-23,2024-06-21,Ms. Salma,Rajshahi,234.0

In [6]:
instructor_group.describe()

           Total Marks                                                       \
                 count        mean        std    min     25%    50%     75%
Instructor
Mr. David          8.0  270.375000  17.606310  248.0  252.75  275.0  285.25
Mr. Karim          6.0  274.166667  12.998718  253.0  270.25  274.0  281.50
Ms. Salma          3.0  249.666667  17.785762  234.0  240.00  246.0  257.50


              max
Instructor
Mr. David   291.0
Mr. Karim   291.0
Ms. Salma   269.0

In [8]:
mean_mark=instructor_group['Total Marks'].mean()
mean_mark

Instructor
Mr. David    270.375000
Mr. Karim    274.166667
Ms. Salma    249.666667
Name: Total Marks, dtype: float64

In [10]:
# fill nan with mean value

df['Total Marks']=df['Total Marks'].fillna(df['Instructor'].map(mean_mark))
df

,StudentID,FullName,CompletionStatus,EnrollmentDate,FinishedDate,Instructor,Location,Total Marks
0,PH0001,Alif Rahman,Completed,2024-09-01,2024-12-23,Ms. Salma,Khulna,249.666667
1,PH0002,Fatima Akhter,Completed,2024-08-11,2024-11-07,Mr. Karim,Dhaka,271.000000
2,PH0003,Imran Hossain,Completed,2024-05-08,2024-08-08,Ms. Salma,Dhaka,269.000000
3,PH0004,Jannatul Ferdous,Completed,2024-07-05,2024-09-23,Mr. Karim,Khulna,270.000000
4,PH0005,Kamal Uddin,Completed,2024-02-01,2024-04-17,Mr. David,Sylhet,254.000000
5,PH0006,Laila Begum,Completed,2024-09-07,2024-12-31,Mr. David,Khulna,272.000000
6,PH0007,Mahmudul Hasan,Completed,2024-06-07,2024-07-20,Mr. David,Chattogram,249.000000
7,PH0008,Nadia Islam,Completed,2024-03-22,2024-05-01,Ms. Salma,Khulna,246.000000
8,PH0009,Omar Faruq,Completed,2024-02-12,2024-06-08,Mr. Karim,Dhaka,291.000000
9,PH0010,Priya Sharma,Completed,2024-06-19,2024-08-19,Mr. David,Dhaka,286.000000
10,PH0011,Rahim Sheikh,Completed,2024-03-14,2024-06-11,Mr. Karim,Sylhet,283.000000
11,PH0012,Sadia Chowdhury,Completed,2024-08-04,2024-10-25,Mr. Karim,Sylhet,274.166667
12,PH0013,Tanvir Ahmed,Completed,2024-06-07,2024-08-03,Mr. David,Dhaka,248.000000
13,PH0014,Urmi Akter,Completed,2024-01-04,2024-03-23,Mr. David,Sylhet,285.000000
14,PH0015,Wahiduzzaman,Completed,2024-02-22,2024-05-16,Mr. David,Rajshahi,291.000000
15,PH0016,Ziaur Rahman,Completed,2024-03-23,2024-06-21,Ms. Salma,Rajshahi,234.000000
16,PH0017,Afsana Mimi,Completed,2024-01-18,2024-03-16,Mr. David,Khulna,270.375000
17,PH0018,Babul Ahmed,Completed,2024-06-23,2024-09-20,Mr. David,Dhaka,278.000000
18,PH0019,Faria Rahman,Completed,2024-04-19,2024-08-17,Mr. Karim,Sylhet,277.000000
19,PH0020,Tariq Hasan,Completed,2024-07-21,2024-10-11,Mr. Karim,Khulna,253.000000